hw_interface_plugin: "mrs_usv_ardurover_api/Api"

mavros_timeout: 5.0 # [s]

position_cmd_map: false

simulated_rtk:
  utm_zone: "32T"
  utm_x: 465710.758973
  utm_y: 5249465.43086
  amsl: 340.0

inputs:
  position:      true
  control_group: false
  attitude_rate: false
  attitude:      false
  velocity_hdg_rate: true

outputs:
  distance_sensor:      false
  gnss:                 true
  rtk:                  true
  imu:                  true
  altitude:             true
  magnetometer_heading: true
  magnetic_field:       true
  rc_channels:          false
  battery_state:        true
  position:             true
  orientation:          true
  velocity:             true
  angular_velocity:     true
  odometry:             true
  ground_truth:         true
